blueprints/common/partials/s3_bucket.hbs

* add AccessControl
* add LifeCycleConfiguration
* use "tags" partial

Refactor S3 bucket

---

blueprints/common/base-all.hbs
blueprints/common/partials/autoscaling_group.hbs
blueprints/common/partials/ec2_instance.hbs
blueprints/common/partials/ec2_securitygroup.hbs
blueprints/common/partials/ec2_securitygroupegress.hbs
blueprints/common/partials/ec2_securitygroupingress.hbs
blueprints/common/partials/ecs_containerdefinition.hbs
blueprints/common/partials/ecs_service.hbs
blueprints/common/partials/ecs_taskdefinition.hbs
blueprints/common/partials/s3_bucket.hbs
lib/build.js
package-lock.json
package.json

This PR contains lots of little changes, mostly to EC2 stuff..

Several small changes

---

blueprints/common/base-all.hbs
blueprints/common/partials/certificatemanager_certificate.hbs
blueprints/common/partials/efs_filesystem.hbs
blueprints/common/partials/route53_hostedzone.hbs
package-lock.json
package.json

Update the ACM Certificate and Route53 partials.

ACM Cert updates

---

lib/refresh.js
lib/utilities.js
scripts/refresh.js

* works with --profile argument
* handles missing/unknown AMI images
* allows 'static' AMI images

Update cfn-refresh to better handle unknowns

---

blueprints/common/base-all.hbs
blueprints/common/partials/cloudwatch_alarm.hbs
blueprints/common/partials/codebuild_project.hbs
blueprints/common/partials/rds_instance.hbs

Updates/Adds:
* New CodeBuild project partial
* Update CloudWatch Alarms
* Change RDS DBInstance partial

Partials work

---

blueprints/common/base-all.hbs
blueprints/common/partials/ec2_natgateway.hbs
blueprints/common/partials/ec2_route.hbs
blueprints/common/partials/ec2_vpcendpoint.hbs

This PR adds EC2 SubnetNetworkAclAssociations and updates several other EC2 networking partials.

update ec2 partials

---

blueprints/common/partials/ec2_subnetnetworkaclassociation.hbs

whoops - forgot to add this one.

add EC2SubnetNetworkAclAssociations partial

---

blueprints/common/base-all.hbs
blueprints/common/partials/cloudwatch_compositealarm.hbs
blueprints/common/partials/inspector_assessmenttarget.hbs
blueprints/common/partials/inspector_assessmenttemplate.hbs
blueprints/common/partials/inspector_resourcegroup.hbs

* AWS Inspector
* CloudWatch CompositeAlarm

Add new partials

---

lib/diff.js

This small change should make it possible to automate the process of checking for stack differences.

count the number of diffs and use that as an exit code

---

blueprints/common/base-all.hbs
blueprints/common/partials/cloudfront_distribution.hbs
blueprints/common/partials/cloudfront_originaccessidentity.hbs
blueprints/common/partials/cloudtrail_trail.hbs
blueprints/common/partials/cloudwatch_alarm.hbs
blueprints/common/partials/lambda_function.hbs
blueprints/common/partials/logs_metricfilter.hbs
blueprints/common/partials/route53_recordset.hbs
blueprints/common/partials/s3_bucket.hbs

This PR contains a few small things and a couple of larger things.
* new CloudFront partials
* updated S3 bucket partial
* add [optional] CW Alarms to Lambda function
* slight tweaks to CW Alarms

New updated partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/pinpoint_app.hbs

Adding basic AWS Pinpoint App partial.

Create Pinpoint App partial

---

blueprints/common/base-all.hbs
blueprints/common/partials/ecr_repository.hbs
blueprints/common/partials/route53_recordset.hbs

This PR adds basic Elastic Container Registry capability.

Add AWS ECR

---

yarn.lock

This PR updates the NPM modules to their latest version.

Update NPM modules

---

blueprints/common/partials/s3_accesspoint.hbs
blueprints/common/partials/s3_bucket.hbs

This PR adds an S3 Access Point partial and updates the S3 Bucket partial.

S3 updates

---

blueprints/common/partials/s3_bucket.hbs

This PR updates several small S3 properties mostly centered around monitoring capabilities.

Update s3 bucket

---

blueprints/common/partials/s3_bucket.hbs

This PR simplifies some of the S3 bucket partial components; specifically the replication config.

Simplify S3 bucket replication partial

---

blueprints/common/base-all.hbs
blueprints/common/partials/wafv2_ipset.hbs
blueprints/common/partials/wafv2_webacl.hbs

This small PR adds 2 WAFv2 partials, which are enough to create a basic WAF config.

Add basic WAFv2 partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/autoscaling_group.hbs
blueprints/common/partials/autoscaling_launchconfiguration.hbs
blueprints/common/partials/autoscaling_scheduledaction.hbs
blueprints/common/partials/cloudwatch_alarm.hbs
blueprints/common/partials/codedeploy_application.hbs
blueprints/common/partials/codedeploy_deploymentgroup.hbs
blueprints/common/partials/cognito_userpooldomain.hbs
blueprints/common/partials/ec2_instance.hbs
blueprints/common/partials/ec2_launchtemplate.hbs
blueprints/common/partials/ec2_vpcendpoint.hbs
blueprints/common/partials/route53_recordset.hbs
lib/build.js
lib/diff.js
lib/process-template.js
lib/utilities.js

The build process in `lib/utilities.js` still needs work.  😦

Stack name overhaul

---

blueprints/common/base-all.hbs
blueprints/common/partials/wafv2_webaclassociation.hbs

This PR adds WAVv2 web ACL associations.

Add WAFv2 web ACL association partial

---

blueprints/common/partials/apigateway_deployment.hbs
blueprints/common/partials/apigateway_method.hbs
blueprints/common/partials/apigateway_resource.hbs
blueprints/common/partials/apigateway_restapi.hbs
blueprints/common/partials/apigatewayv2_domainname.hbs
blueprints/common/partials/apigatewayv2_integration.hbs
blueprints/common/partials/apigatewayv2_route.hbs
blueprints/common/partials/certificatemanager_certificate.hbs

This PR updates the API Gateway partials to better deal with names.

Sanitize API Gateway partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/ec2_transitgatewayattachment.hbs
blueprints/common/partials/transfer_server.hbs
blueprints/common/partials/transfer_user.hbs

This PR adds transfer family capability to cfn-builder

added transfer family

---

blueprints/common/partials/cloudwatch_alarm.hbs
blueprints/common/partials/logs_metricfilter.hbs

This PR updates the CloudWatch logs and alarm partials.

Update CloudWatch partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/ec2_securitygroup.hbs
blueprints/common/partials/rds_instance.hbs
blueprints/common/partials/secretsmanager_resourcepolicy.hbs
blueprints/common/partials/secretsmanager_secret.hbs

This PR updates several partials and adds a new SecretsManager ResourcePolicy partial.

Partial updates

---

blueprints/common/base-all.hbs
blueprints/common/partials/rds_dbcluster.hbs
blueprints/common/partials/rds_instance.hbs

This PR updates the RDS partials and adds a new Aurora Cluster partial.

Update RDS partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/iam_oidcprovider.hbs
lib/process-template.js

This PR adds the OIDC provider that is used by GitHub Actions to authenticate to AWS.  It also adds a "split" Handlebars function that is useful for providing arrays to partial parameters.

OIDC provider

---

blueprints/common/partials/backup_backupplan.hbs
blueprints/common/partials/backup_backupselection.hbs
blueprints/common/partials/backup_backupvault.hbs
blueprints/common/partials/logs_metricfilter.hbs
blueprints/common/partials/logs_subscriptionfilter.hbs

This PR adds AWS Backup partials.
It also does some slight CW Logs work.

Add AWS Backup partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/ecs_cluster.hbs
blueprints/common/partials/ecs_containerdefinition.hbs
blueprints/common/partials/ecs_service.hbs
blueprints/common/partials/ecs_taskdefinition.hbs

This PR updates the Elastic Container Service blueprints and adds a "Cluster" blueprint.

ECS Updates

---

blueprints/common/partials/ce_anomalymonitor.hbs
blueprints/common/partials/ce_anomalysubscription.hbs

This PR adds the ability to create Cost Explorer resources in CFN.

Add Cost Explorer Blueprints

---

blueprints/common/base-all.hbs
blueprints/common/partials/ce_anomalysubscription.hbs

This PR updates the CE resources and makes them available in the base-all recipes.

Add CE resources

---

blueprints/common/partials/elasticloadbalancingv2_loadbalancer.hbs
blueprints/common/partials/route53_recordset.hbs
blueprints/common/partials/route53_recordsetgroup.hbs
lib/process-template.js

This PR does some minor refactoring to the Route53 RecordSet partials and adds a new "ifArray" helper function.

Minor updates

---

blueprints/common/base-all.hbs
blueprints/common/partials/apigateway_basepathmapping.hbs
blueprints/common/partials/apigateway_domain_name.hbs

Updates API Gateway (V1) Domain Name from "custom" to official support.
Adds BasePathMapping for API Gateway (V1)

partials init

---

blueprints/common/partials/ecs_containerdefinition.hbs
blueprints/common/partials/ecs_service.hbs

This is a work in progress for ECS partials.  There will probably be more to come from this.

Update ECS partials

---

blueprints/common/partials/codedeploy_deploymentgroup.hbs

This PR configures the Blue/Green deployment config for CodeDeploy.

Add Blue/Green deployment config

---

blueprints/common/base-all.hbs
blueprints/common/partials/apigateway_vpclink.hbs
blueprints/common/partials/apigatewayv2_integration.hbs
blueprints/common/partials/apigatewayv2_vpclink.hbs
blueprints/common/partials/autoscaling_scheduledaction.hbs
blueprints/common/partials/batch_computeenvironment.hbs
blueprints/common/partials/batch_jobdefinition.hbs
blueprints/common/partials/batch_jobqueue.hbs
blueprints/common/partials/cloudformation_macro.hbs
blueprints/common/partials/cognito_userpool.hbs
blueprints/common/partials/ecs_containerdefinition.hbs
blueprints/common/partials/ecs_service.hbs
blueprints/common/partials/elasticache_parametergroup.hbs
blueprints/common/partials/elasticache_replicationgroup.hbs
blueprints/common/partials/elasticache_serverlesscache.hbs
blueprints/common/partials/elasticloadbalancingv2_listener.hbs
blueprints/common/partials/elasticloadbalancingv2_listenercertificate.hbs
blueprints/common/partials/elasticloadbalancingv2_loadbalancer.hbs
blueprints/common/partials/opensearchservice_domain.hbs
blueprints/common/partials/route53_recordset.hbs
blueprints/common/partials/scheduler_schedule.hbs
blueprints/common/partials/scheduler_schedulegroup.hbs
blueprints/common/partials/securityhub_configurationpolicy.hbs
blueprints/common/partials/securityhub_standard.hbs
lib/process-template.js

This pull request includes several updates to the `blueprints/common/base-all.hbs` file and various partials in the `blueprints/common/partials` directory. The changes focus on adding support for new AWS resources and improving existing templates for better functionality and flexibility.
* Added support for `APIGatewayV2VpcLinks`, `APIGatewayVpcLinks`, `BatchComputeEnvironments`, `BatchJobDefinitions`, `BatchJobQueues`, `CloudFormationMacros`, `ElastiCacheServerlessCaches`, `ElasticLoadBalancerV2Listeners`, `ElasticLoadBalancerV2ListenerCertificates`, `SchedulerSchedules`, `SchedulerScheduleGroups`, `SecurityHubConfigurationPolicies`, and `SecurityHubStandards`. [[1]](diffhunk://#diff-0655b474d944b03a62d5562c60782b2222b910fbe1fc84e3407c0ec5dd9020a2R97-R104) …

Add / Update Partials

---

blueprints/common/base-all.hbs
blueprints/common/partials/applicationautoscaling_scalabletarget.hbs
blueprints/common/partials/applicationautoscaling_scalingpolicy.hbs

This PR adds some new partials for dealing with Application Autoscaling.

Add autoscaling blueprints

---

blueprints/common/partials/ecs_containerdefinition.hbs

This PR fixes a problem with setting Essential to anything but "true".

Update Essential test
